/* Generated By:JavaCC: Do not edit this line. LALGConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface LALGConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int LPAREN = 5;
  /** RegularExpression Id. */
  int RPAREN = 6;
  /** RegularExpression Id. */
  int COMMA = 7;
  /** RegularExpression Id. */
  int DOT = 8;
  /** RegularExpression Id. */
  int PROGRAM = 9;
  /** RegularExpression Id. */
  int VAR = 10;
  /** RegularExpression Id. */
  int CONST = 11;
  /** RegularExpression Id. */
  int REAL = 12;
  /** RegularExpression Id. */
  int INTEGER = 13;
  /** RegularExpression Id. */
  int PROCEDURE = 14;
  /** RegularExpression Id. */
  int BEGIN = 15;
  /** RegularExpression Id. */
  int END = 16;
  /** RegularExpression Id. */
  int DIGIT = 17;
  /** RegularExpression Id. */
  int NUM = 18;
  /** RegularExpression Id. */
  int COLON = 19;
  /** RegularExpression Id. */
  int SEMICOLON = 20;
  /** RegularExpression Id. */
  int READ = 21;
  /** RegularExpression Id. */
  int WRITE = 22;
  /** RegularExpression Id. */
  int DO = 23;
  /** RegularExpression Id. */
  int IF = 24;
  /** RegularExpression Id. */
  int THEN = 25;
  /** RegularExpression Id. */
  int ELSE = 26;
  /** RegularExpression Id. */
  int WHILE = 27;
  /** RegularExpression Id. */
  int FOR = 28;
  /** RegularExpression Id. */
  int TO = 29;
  /** RegularExpression Id. */
  int ID = 30;
  /** RegularExpression Id. */
  int PLUS = 31;
  /** RegularExpression Id. */
  int MINUS = 32;
  /** RegularExpression Id. */
  int MUL = 33;
  /** RegularExpression Id. */
  int DIV = 34;
  /** RegularExpression Id. */
  int ASSIGN = 35;
  /** RegularExpression Id. */
  int EQUALS = 36;
  /** RegularExpression Id. */
  int GREATEREQUAL = 37;
  /** RegularExpression Id. */
  int LESSEREQUAL = 38;
  /** RegularExpression Id. */
  int NOTEQUAL = 39;
  /** RegularExpression Id. */
  int GREATER = 40;
  /** RegularExpression Id. */
  int LESSER = 41;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\n\"",
    "\"\\r\"",
    "<token of kind 4>",
    "\"(\"",
    "\")\"",
    "\",\"",
    "\".\"",
    "\"program\"",
    "\"var\"",
    "\"const\"",
    "\"real\"",
    "\"integer\"",
    "\"procedure\"",
    "\"begin\"",
    "\"end\"",
    "<DIGIT>",
    "<NUM>",
    "\":\"",
    "\";\"",
    "\"read\"",
    "\"write\"",
    "\"do\"",
    "\"if\"",
    "\"then\"",
    "\"else\"",
    "\"while\"",
    "\"for\"",
    "\"to\"",
    "<ID>",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\":=\"",
    "\"=\"",
    "\">=\"",
    "\"<=\"",
    "\"<>\"",
    "\">\"",
    "\"<\"",
  };

}
